"""removed department from supportstaff

Revision ID: 0d9848a862dd
Revises: 8369544734dc
Create Date: 2024-08-06 22:41:23.805282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d9848a862dd'
down_revision = '8369544734dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
