"""empty message

Revision ID: 74ce7c6699f2
Revises: 9dc114b671ee
Create Date: 2024-08-20 13:01:39.687807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ce7c6699f2'
down_revision = '9dc114b671ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.drop_column('explanation')

    # ### end Alembic commands ###
