"""Add options and course_options

Revision ID: 9dc114b671ee
Revises: e8500375bb07
Create Date: 2024-08-19 19:00:02.797815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc114b671ee'
down_revision = 'e8500375bb07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.drop_column('course_name')
        batch_op.drop_column('options')

    # ### end Alembic commands ###
