"""empty message

Revision ID: df3114b51b7f
Revises: 74ce7c6699f2
Create Date: 2024-08-20 18:09:45.285023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df3114b51b7f'
down_revision = '74ce7c6699f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_problems', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
